services:
  postgres:
    container_name: amigoscode_pg
    image: postgres
    environment:
      - POSTGRES_USER=amigoscode
      - POSTGRES_PASSWORD=password
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

#  customer:
#    container_name: amigoscode_customer
#    image: customer:latest
#    ports:
#      - "3000:3000"
#    networks:
#      - postgres
#    restart: always
#    depends_on:
#      - postgres

  rabbitmq:
    container_name: amigoscode_mq
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  jaeger:
    container_name: amigoscode_jaeger
    image: jaegertracing/all-in-one
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
